[package]
name = "assignment_7"
version = "0.1.0"
authors = ["Aamir-Hanif <aamirhanif234@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

piaic_batch3 = {path = "../piaic_batch3"}
